# docker compose -f docker-compose.dev.yml up --build

services:
  dev-server:
    image: node:lts-alpine
    working_dir: /app
    ports:
      - "5173:5173"
      - "8080:8080"
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - .env
    command: sh -c "npm install --include=dev && (npm run dev &) && sleep 5 && npx tsx watch --env-file=.env server/index.ts"
